services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: student_portal
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: student
      DB_USER: postgres
      DB_PASSWORD: postgres
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "300"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: student_portal_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: student
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - student_portal_postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./backend/database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: student_portal_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@student.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db
    restart: unless-stopped

volumes:
  student_portal_postgres_data: